=== egorderzhanovich/HM/src/main/java/may14/employee.dtd
<!ELEMENT hospital (employee*)>
        <!ELEMENT employee (name,job,department,workExperience)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT job (#PCDATA)>
        <!ELEMENT department (#PCDATA)>
        <!ELEMENT workExperience (#PCDATA)>
        <!ATTLIST employee id CDATA #REQUIRED>

=== egorderzhanovich/HM/src/main/java/may14/employees.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE hospital SYSTEM "employee.dtd">

<hospital>
    <employee id="1">
        <name>Egor Derzhanovich</name>
        <job>Therapist</job>
        <department>therapy</department>
        <workExperience>5</workExperience>
    </employee>
    <employee id="2">
        <name>Egor Derzhanovich</name>
        <job>Therapist</job>
        <department>therapy</department>
        <workExperience>5</workExperience>
    </employee>
    <employee id="3">
        <name>Anna Anna</name>
        <job>De</job>
        <department>therapy</department>
        <workExperience>5</workExperience>
    </employee>
    <employee id="4">
        <name>Egor Derzhanovich</name>
        <job>Nurse</job>
        <department>therapy</department>
        <workExperience>5</workExperience>
    </employee>
</hospital>
